# The Site Configuration
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# this means to ignore newlines until "baseurl:"
# List of community-curated resources to find topical remote freelance & contract work for software developers, web designers, and more!
# the subpath of your site, e.g. /blog
# the base hostname & protocol for your site, e.g. https://ezees.github.io/mrtong.github.io/

twitter_username: werty35169010
github_username:  Ezees
description:   List of community-curated resources to find topical remote freelance & contract work for software developers, web designers, and more!
baseurl: "https://ezees.github.io/mrtong.github.io/" 


url: https://ezees.github.io/mrtong.github.io
title: Mr.TonG s blog
author: jawolaray
email: wertylaray@gmail.com
twitter_username: werty35169010
github_username:  Ezees
layouts_dir: _layouts
paginate: 10

collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
 # profile: false
  blanklines: false
  ignore:
    envs: [development]


markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-postcss

postcss:
 # cache: false


# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://res.cloudinary.com/dvmwx4naf/image/upload/c_fill,g_face,h_300,w_300/r_max/cld-sample-2.jpg'
 "MediaManager.get().url().transformation(new Transformation()
  .gravity("face").height(300).width(300).crop("fill").chain()
  .radius("max")).generate("cld-sample-2.jpg");"

# cl_image_tag("cld-sample-2.jpg", :transformation=>[
  {:gravity=>"face", :height=>300, :width=>300, :crop=>"fill"},
  {:radius=>"max"}
  ])"

# boolean type, the global switch for TOC in posts.

avatar: "assets/img/avatar.jpg"

# boolean type, the global switch for TOC in posts.
toc: true

comments: true
  active: 
disqus:
shortname: https-ezees-github-io-mrtong-github-io 


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - tools
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore


enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
    about: about
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
    about: /about/:name/